site_name: WasteNet MLOps
site_author: Mohamed
site_description: Documentation du pipeline MLOps de classification d'ordures

nav:
  - Accueil: index.md
  - Demarrage: getting-started.md
  - Architecture: architecture.md

theme: readthedocs